// Next.js API route support: https://nextjs.org/docs/api-routes/introduction
import type { NextApiRequest, NextApiResponse } from 'next'
import { realEstate } from '../../utils/realEstate';
import { unstable_getServerSession } from "next-auth/next"
import { authOptions } from "./auth/[...nextauth]"
import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

type Data = any
//testy
const users = [
    {
        "customer_id": "cus_NNHyI8Z0V6quyq",
        "created": "2023-02-17 17:07",
        "name": "",
        "description": "",
        "email": "patriciacavato@gmail.com",
        "net_volume": 147,
        "gross_volume": 147,
        "payment_count": 3,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-02-24 18:11",
        "last_payment": "2023-04-27 18:14",
        "mrr": 49,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NKdDzH8tyeiNF9",
        "created": "2023-02-10 14:51",
        "name": "",
        "description": "",
        "email": "JJY12@MY.FSU.EDU",
        "net_volume": 147,
        "gross_volume": 147,
        "payment_count": 3,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-02-17 15:58",
        "last_payment": "2023-04-17 15:58",
        "mrr": 49,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NCsvP2Gm6CjnUw",
        "created": "2023-01-20 22:33",
        "name": "",
        "description": "",
        "email": "kurtova.e@gmail.com",
        "net_volume": 150,
        "gross_volume": 200,
        "payment_count": 4,
        "refund_volume": 50,
        "dispute_losses": 0,
        "first_payment": "2023-01-21 19:04",
        "last_payment": "2023-03-21 20:21",
        "mrr": 0,
        "mrr_change_thirty_days": -50,
        "outstanding_balance": 0,
        "active_subscriptions": 0,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NktXU4JuZsVnli",
        "created": "2023-04-21 17:27",
        "name": "",
        "description": "",
        "email": "punchy104@gmail.com",
        "net_volume": 53.5,
        "gross_volume": 53.5,
        "payment_count": 1,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-04-21 17:29",
        "last_payment": "2023-04-21 17:29",
        "mrr": 53.5,
        "mrr_change_thirty_days": 53.5,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_Ne4zbufiRKYyEW",
        "created": "2023-04-03 12:49",
        "name": "",
        "description": "",
        "email": "miguelclemino@gmail.com",
        "net_volume": 0,
        "gross_volume": 50,
        "payment_count": 1,
        "refund_volume": 50,
        "dispute_losses": 0,
        "first_payment": "2023-04-03 12:52",
        "last_payment": "2023-04-03 12:52",
        "mrr": 50,
        "mrr_change_thirty_days": 50,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_N98zoWYJxpP9dK",
        "created": "2023-01-10 22:53",
        "name": "Min L Yong",
        "description": "",
        "email": "linandyongx@gmail.com",
        "net_volume": 200,
        "gross_volume": 200,
        "payment_count": 4,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-01-17 23:59",
        "last_payment": "2023-04-17 23:54",
        "mrr": 50,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NmuIvLevEmy741",
        "created": "2023-04-27 02:23",
        "name": "",
        "description": "",
        "email": "cj.co@outlook.com",
        "net_volume": 449.4,
        "gross_volume": 449.4,
        "payment_count": 1,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-04-27 02:24",
        "last_payment": "2023-04-27 02:24",
        "mrr": 37.45,
        "mrr_change_thirty_days": 37.45,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NdPzbi7WXeXYcF",
        "created": "2023-04-01 18:27",
        "name": "",
        "description": "",
        "email": "sarahisk@gmail.com",
        "net_volume": 100,
        "gross_volume": 100,
        "payment_count": 2,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-04-01 18:29",
        "last_payment": "2023-05-01 19:31",
        "mrr": 50,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_N9CHijIuXHSr4h",
        "created": "2023-01-11 02:17",
        "name": "Jefferey Chheuy",
        "description": "",
        "email": "jefferey.chheuy@gmail.com",
        "net_volume": 200,
        "gross_volume": 200,
        "payment_count": 4,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-01-18 03:19",
        "last_payment": "2023-04-18 03:21",
        "mrr": 50,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_N91Qcx75pJjXsj",
        "created": "2023-01-10 15:04",
        "name": "Joshua M Salgado",
        "description": "",
        "email": "theroyaljchannel@gmail.com",
        "net_volume": 200,
        "gross_volume": 200,
        "payment_count": 4,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-01-17 16:07",
        "last_payment": "2023-04-17 16:12",
        "mrr": 50,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_Mz55anfMi2fTaZ",
        "created": "2022-12-15 02:12",
        "name": "Alberto Olivo",
        "description": "",
        "email": "albertojoseolivo@gmail.com",
        "net_volume": 150,
        "gross_volume": 150,
        "payment_count": 5,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2022-12-15 02:12",
        "last_payment": "2023-04-15 03:13",
        "mrr": 30,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NZhcYfLRdrpgPH",
        "created": "2023-03-22 20:24",
        "name": "",
        "description": "",
        "email": "flcoastrealestateagent@gmail.com",
        "net_volume": 100,
        "gross_volume": 100,
        "payment_count": 2,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-03-22 20:27",
        "last_payment": "2023-04-22 21:29",
        "mrr": 50,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "7e4bcbbc-7a7f-40be-ba0b-93f221e2cb56",
        "Affiliate (metadata)": "Jazmin Kirkman <jazminkirkman@gmail.com>",
        "Campaign (metadata)": "Fetchit Ambassadors: 50% commission on all payments",
        "Link (metadata)": "jazmin",
        "View in Rewardful (metadata)": "https://app.getrewardful.com/referrals/7e4bcbbc-7a7f-40be-ba0b-93f221e2cb56",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NWLI4tY8hU5o9A",
        "created": "2023-03-13 21:09",
        "name": "",
        "description": "",
        "email": "becky_ta@yahoo.com",
        "net_volume": 100,
        "gross_volume": 100,
        "payment_count": 2,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-03-13 21:09",
        "last_payment": "2023-04-13 22:11",
        "mrr": 50,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_N1yNJTcXcL5pJl",
        "created": "2022-12-22 19:27",
        "name": "Lindsey Severt",
        "description": "",
        "email": "lindseysevert.spg@gmail.com",
        "net_volume": 50,
        "gross_volume": 50,
        "payment_count": 5,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2022-12-22 19:28",
        "last_payment": "2023-04-22 20:28",
        "mrr": 10,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NHMXh3PZOyO5Wx",
        "created": "2023-02-01 21:25",
        "name": "",
        "description": "",
        "email": "info@floraluxehomes.com",
        "net_volume": 200,
        "gross_volume": 200,
        "payment_count": 4,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-02-01 21:27",
        "last_payment": "2023-05-01 22:37",
        "mrr": 50,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NKnTswRnkoZEoX",
        "created": "2023-02-11 01:28",
        "name": "",
        "description": "",
        "email": "alexandr.dron@gmail.com",
        "net_volume": 98,
        "gross_volume": 98,
        "payment_count": 2,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-02-18 02:36",
        "last_payment": "2023-03-18 02:30",
        "mrr": 49,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 49,
        "active_subscriptions": 0,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_Mz5DmQXVNcBd6j",
        "created": "2022-12-15 02:19",
        "name": "Shaun Capoferri",
        "description": "",
        "email": "capoferricustoms@gmail.com",
        "net_volume": 120,
        "gross_volume": 120,
        "payment_count": 4,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2022-12-15 02:19",
        "last_payment": "2023-03-15 03:21",
        "mrr": 0,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 0,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_N95VxkJq1Ao9OX",
        "created": "2023-01-10 19:17",
        "name": "james martell",
        "description": "",
        "email": "james@martellgroup.com",
        "net_volume": 200,
        "gross_volume": 200,
        "payment_count": 4,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-01-17 20:18",
        "last_payment": "2023-04-20 20:29",
        "mrr": 50,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_Mz56thY4WoOvZ9",
        "created": "2022-12-15 02:13",
        "name": "Craig Holland",
        "description": "",
        "email": "hollandproperty2022@gmail.com",
        "net_volume": 150,
        "gross_volume": 150,
        "payment_count": 5,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2022-12-15 02:13",
        "last_payment": "2023-04-15 03:17",
        "mrr": 30,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NX715s9E6tRAVf",
        "created": "2023-03-15 22:27",
        "name": "Jacinda A Neustel",
        "description": "",
        "email": "jtradeproperties@gmail.com",
        "net_volume": 50,
        "gross_volume": 50,
        "payment_count": 2,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-03-15 22:29",
        "last_payment": "2023-04-15 23:30",
        "mrr": 25,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_N9V2khuWsKwIkI",
        "created": "2023-01-11 21:41",
        "name": "Alan T Joshua",
        "description": "",
        "email": "Alan_Joshua@hotmail.com",
        "net_volume": 200,
        "gross_volume": 200,
        "payment_count": 4,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-01-18 22:44",
        "last_payment": "2023-04-18 22:43",
        "mrr": 50,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_N945GEliU1Mq0M",
        "created": "2023-01-10 17:49",
        "name": "Christian Bachelder Bachelder",
        "description": "",
        "email": "christian.j.bachelder@gmail.com",
        "net_volume": 200,
        "gross_volume": 200,
        "payment_count": 4,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-01-17 18:52",
        "last_payment": "2023-04-17 18:52",
        "mrr": 50,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NkCyjanBd3TQ4d",
        "created": "2023-04-19 21:29",
        "name": "",
        "description": "",
        "email": "connorce814@gmail.com",
        "net_volume": 53.5,
        "gross_volume": 53.5,
        "payment_count": 1,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-04-19 21:30",
        "last_payment": "2023-04-19 21:30",
        "mrr": 53.5,
        "mrr_change_thirty_days": 53.5,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NdxEpmCSGGt5YW",
        "created": "2023-04-03 04:48",
        "name": "",
        "description": "",
        "email": "jeffrey.lage@gmail.com",
        "net_volume": 50,
        "gross_volume": 50,
        "payment_count": 1,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-04-03 12:07",
        "last_payment": "2023-04-03 12:07",
        "mrr": 50,
        "mrr_change_thirty_days": 50,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NSvclw9KommHrv",
        "created": "2023-03-04 18:24",
        "name": "",
        "description": "",
        "email": "lucasserau@hotmail.com",
        "net_volume": 100,
        "gross_volume": 100,
        "payment_count": 2,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-03-04 18:25",
        "last_payment": "2023-04-04 19:28",
        "mrr": 50,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NdR8gxqisypnRD",
        "created": "2023-04-01 19:38",
        "name": "",
        "description": "",
        "email": "fetchit@snoozymoose.com",
        "net_volume": 100,
        "gross_volume": 100,
        "payment_count": 2,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-04-01 19:43",
        "last_payment": "2023-05-01 20:50",
        "mrr": 50,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NH1BuzLpq81lRd",
        "created": "2023-01-31 23:22",
        "name": "",
        "description": "",
        "email": "ashleynora@gmail.com",
        "net_volume": 147,
        "gross_volume": 147,
        "payment_count": 3,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-02-08 00:24",
        "last_payment": "2023-04-08 00:25",
        "mrr": 49,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_N9USreFyQWdFjq",
        "created": "2023-01-11 21:04",
        "name": "Bryan Souza",
        "description": "",
        "email": "bryansouza@gmail.com",
        "net_volume": 150,
        "gross_volume": 150,
        "payment_count": 3,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-01-18 22:05",
        "last_payment": "2023-03-18 22:08",
        "mrr": 0,
        "mrr_change_thirty_days": -50,
        "outstanding_balance": 0,
        "active_subscriptions": 0,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NfPWosojI98Vab",
        "created": "2023-04-07 02:06",
        "name": "",
        "description": "",
        "email": "nybose@gmail.com",
        "net_volume": 0,
        "gross_volume": 50,
        "payment_count": 1,
        "refund_volume": 50,
        "dispute_losses": 0,
        "first_payment": "2023-04-07 13:46",
        "last_payment": "2023-04-07 13:46",
        "mrr": 50,
        "mrr_change_thirty_days": 50,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NKkajCXygMMxHA",
        "created": "2023-02-10 22:29",
        "name": "",
        "description": "",
        "email": "tylerjj0211@gmail.com",
        "net_volume": 49,
        "gross_volume": 147,
        "payment_count": 3,
        "refund_volume": 0,
        "dispute_losses": 98,
        "first_payment": "2023-02-17 23:36",
        "last_payment": "2023-04-17 23:34",
        "mrr": 49,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_MzL9QGDBjpoOFg",
        "created": "2022-12-15 18:47",
        "name": "Chad Gourley",
        "description": "",
        "email": "chadgourley1@gmail.com",
        "net_volume": 150,
        "gross_volume": 150,
        "payment_count": 5,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2022-12-15 18:48",
        "last_payment": "2023-04-15 19:53",
        "mrr": 30,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NSdOKdOOePd4Nn",
        "created": "2023-03-03 23:35",
        "name": "",
        "description": "",
        "email": "rf@lettventures.com",
        "net_volume": 99,
        "gross_volume": 99,
        "payment_count": 2,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-03-11 00:37",
        "last_payment": "2023-04-14 03:57",
        "mrr": 50,
        "mrr_change_thirty_days": 1,
        "outstanding_balance": 49,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NPwdHBq8e3cWwr",
        "created": "2023-02-24 19:15",
        "name": "",
        "description": "",
        "email": "vincent.omelio@gmail.com",
        "net_volume": 150,
        "gross_volume": 150,
        "payment_count": 3,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-02-27 01:16",
        "last_payment": "2023-04-27 02:21",
        "mrr": 50,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NPtAVQ819YUG12",
        "created": "2023-02-24 15:40",
        "name": "",
        "description": "",
        "email": "nsrobbins@gmail.com",
        "net_volume": 49,
        "gross_volume": 49,
        "payment_count": 1,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-03-03 16:44",
        "last_payment": "2023-03-03 16:44",
        "mrr": 0,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 0,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NLvOl1BrSRfuXE",
        "created": "2023-02-14 01:42",
        "name": "",
        "description": "",
        "email": "tysonwaggener@gmail.com",
        "net_volume": 150,
        "gross_volume": 150,
        "payment_count": 3,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-02-14 01:45",
        "last_payment": "2023-04-14 02:45",
        "mrr": 50,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_Nkx4nyWpiAQIR5",
        "created": "2023-04-21 21:06",
        "name": "",
        "description": "",
        "email": "elee9430@yahoo.com",
        "net_volume": 53.5,
        "gross_volume": 53.5,
        "payment_count": 1,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-04-21 21:07",
        "last_payment": "2023-04-21 21:07",
        "mrr": 53.5,
        "mrr_change_thirty_days": 53.5,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NeBJv0D2Fl50fu",
        "created": "2023-04-03 19:21",
        "name": "",
        "description": "",
        "email": "barraza521@gmail.com",
        "net_volume": 49,
        "gross_volume": 49,
        "payment_count": 1,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-04-10 20:30",
        "last_payment": "2023-04-10 20:30",
        "mrr": 49,
        "mrr_change_thirty_days": 49,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_Na6vTFrjh9jkAo",
        "created": "2023-03-23 22:33",
        "name": "",
        "description": "",
        "email": "oracio@asaphouseoffers.com",
        "net_volume": 100,
        "gross_volume": 100,
        "payment_count": 2,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-03-23 22:36",
        "last_payment": "2023-04-23 23:37",
        "mrr": 50,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_N99qt2FCy9Qxwx",
        "created": "2023-01-10 23:47",
        "name": "Darlene O. Sanchez",
        "description": "",
        "email": "v8vacationhomes@gmail.com",
        "net_volume": 200,
        "gross_volume": 200,
        "payment_count": 4,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-01-18 00:50",
        "last_payment": "2023-04-17 21:52",
        "mrr": 50,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 50,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NN1Ze5JFZc95KM",
        "created": "2023-02-17 00:09",
        "name": "",
        "description": "",
        "email": "anthony@thedavanigroup.com",
        "net_volume": 150,
        "gross_volume": 150,
        "payment_count": 3,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-02-17 00:10",
        "last_payment": "2023-04-17 01:14",
        "mrr": 50,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NCxADu9asuBrKq",
        "created": "2023-01-21 02:56",
        "name": "",
        "description": "",
        "email": "christian.prince99@gmail.com",
        "net_volume": 196,
        "gross_volume": 196,
        "payment_count": 4,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-01-28 03:59",
        "last_payment": "2023-04-28 03:59",
        "mrr": 49,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NOvozPntjej4sr",
        "created": "2023-02-22 02:20",
        "name": "",
        "description": "",
        "email": "taylorskaw@hotmail.com",
        "net_volume": 150,
        "gross_volume": 150,
        "payment_count": 3,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-02-22 02:21",
        "last_payment": "2023-04-22 03:23",
        "mrr": 50,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NKQVDNTqBDVEq5",
        "created": "2023-02-10 01:44",
        "name": "",
        "description": "",
        "email": "rakinzaman@gmail.com",
        "net_volume": 98,
        "gross_volume": 98,
        "payment_count": 2,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-02-17 02:47",
        "last_payment": "2023-03-17 02:46",
        "mrr": 0,
        "mrr_change_thirty_days": -49,
        "outstanding_balance": 0,
        "active_subscriptions": 0,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NRCbG2UKl1Tadp",
        "created": "2023-02-28 03:49",
        "name": "",
        "description": "",
        "email": "aadavidson86@gmail.com",
        "net_volume": 100,
        "gross_volume": 100,
        "payment_count": 2,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-02-28 03:50",
        "last_payment": "2023-03-28 04:54",
        "mrr": 0,
        "mrr_change_thirty_days": -50,
        "outstanding_balance": 0,
        "active_subscriptions": 0,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NCCjlLUOQa5Ete",
        "created": "2023-01-19 02:58",
        "name": "",
        "description": "",
        "email": "nitaylaor@gmail.com",
        "net_volume": 200,
        "gross_volume": 200,
        "payment_count": 4,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-01-19 02:59",
        "last_payment": "2023-04-19 04:05",
        "mrr": 50,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NKKXW9LLrSTlrl",
        "created": "2023-02-09 19:33",
        "name": "",
        "description": "",
        "email": "legacyacquisitionsmd@gmail.com",
        "net_volume": 147,
        "gross_volume": 147,
        "payment_count": 3,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-02-16 20:38",
        "last_payment": "2023-04-16 20:38",
        "mrr": 49,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_N9oe0xaJpm24dF",
        "created": "2023-01-12 17:56",
        "name": "Brandy Monge",
        "description": "",
        "email": "brandymonge@gmail.com",
        "net_volume": 50,
        "gross_volume": 200,
        "payment_count": 4,
        "refund_volume": 0,
        "dispute_losses": 150,
        "first_payment": "2023-01-19 19:01",
        "last_payment": "2023-04-27 19:01",
        "mrr": 50,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NlyQZlXTYGqHoa",
        "created": "2023-04-24 14:34",
        "name": "",
        "description": "",
        "email": "upstateholidays@gmail.com",
        "net_volume": 53.5,
        "gross_volume": 53.5,
        "payment_count": 1,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-04-24 14:35",
        "last_payment": "2023-04-24 14:35",
        "mrr": 53.5,
        "mrr_change_thirty_days": 53.5,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "cd610710-f5b5-4b35-94c0-d1eb2f645deb",
        "Affiliate (metadata)": "David Danesh <daviddanesh5@gmail.com>",
        "Campaign (metadata)": "Fetchit Ambassadors: 50% commission on all payments",
        "Link (metadata)": "david-danesh",
        "View in Rewardful (metadata)": "https://app.getrewardful.com/referrals/cd610710-f5b5-4b35-94c0-d1eb2f645deb",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NatK5Pm8Q1yNPj",
        "created": "2023-03-26 00:34",
        "name": "",
        "description": "",
        "email": "einvestforlife@gmail.com",
        "net_volume": 0,
        "gross_volume": 50,
        "payment_count": 1,
        "refund_volume": 50,
        "dispute_losses": 0,
        "first_payment": "2023-03-26 00:36",
        "last_payment": "2023-03-26 00:36",
        "mrr": 0,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 0,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NPKRjKCL0dhnlr",
        "created": "2023-02-23 03:47",
        "name": "Andrea Mejia",
        "description": "",
        "email": "94amejia@gmail.com",
        "net_volume": 3000,
        "gross_volume": 3000,
        "payment_count": 3,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-02-23 03:47",
        "last_payment": "2023-04-23 04:50",
        "mrr": 1000,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NjYiAWFN3kpoxx",
        "created": "2023-04-18 03:52",
        "name": "",
        "description": "",
        "email": "gcpisciotta@gmail.com",
        "net_volume": 53.5,
        "gross_volume": 53.5,
        "payment_count": 1,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-04-30 20:15",
        "last_payment": "2023-04-30 20:15",
        "mrr": 53.5,
        "mrr_change_thirty_days": 53.5,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NYZCarPldJjKIz",
        "created": "2023-03-19 19:38",
        "name": "",
        "description": "",
        "email": "andrewrcecola@gmail.com",
        "net_volume": 100,
        "gross_volume": 100,
        "payment_count": 2,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-03-19 19:40",
        "last_payment": "2023-04-19 20:44",
        "mrr": 0,
        "mrr_change_thirty_days": -50,
        "outstanding_balance": 0,
        "active_subscriptions": 0,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_N92IIRrhZMJ6xJ",
        "created": "2023-01-10 15:58",
        "name": "Brandon Leffler",
        "description": "",
        "email": "brandweiser@yahoo.com",
        "net_volume": 200,
        "gross_volume": 200,
        "payment_count": 4,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-01-17 16:59",
        "last_payment": "2023-04-17 17:00",
        "mrr": 50,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_MziaguWMLGAWLK",
        "created": "2022-12-16 19:01",
        "name": "Hannah Joy Roche",
        "description": "",
        "email": "hjroche86@gmail.com",
        "net_volume": 150,
        "gross_volume": 150,
        "payment_count": 5,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2022-12-16 19:01",
        "last_payment": "2023-04-16 20:03",
        "mrr": 30,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_Mz52hNsXPDdJ55",
        "created": "2022-12-15 02:08",
        "name": "Joel Felicio",
        "description": "",
        "email": "joel.felicio75@gmail.com",
        "net_volume": 150,
        "gross_volume": 150,
        "payment_count": 5,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2022-12-15 02:08",
        "last_payment": "2023-04-15 03:10",
        "mrr": 30,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_Navhc4rH9vKRD5",
        "created": "2023-03-26 03:01",
        "name": "",
        "description": "",
        "email": "richard.ostertag@icloud.com",
        "net_volume": 49,
        "gross_volume": 49,
        "payment_count": 1,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-04-02 04:25",
        "last_payment": "2023-04-02 04:25",
        "mrr": 49,
        "mrr_change_thirty_days": 49,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NKluPcxWZuZQ5f",
        "created": "2023-02-10 23:50",
        "name": "",
        "description": "",
        "email": "teishaharris38@gmail.com",
        "net_volume": 49,
        "gross_volume": 49,
        "payment_count": 1,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-03-08 23:33",
        "last_payment": "2023-03-08 23:33",
        "mrr": 0,
        "mrr_change_thirty_days": -49,
        "outstanding_balance": 49,
        "active_subscriptions": 0,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NFTmMGqLauFzI5",
        "created": "2023-01-27 20:46",
        "name": "",
        "description": "",
        "email": "nexgeniteamgv@gmail.com",
        "net_volume": 98,
        "gross_volume": 98,
        "payment_count": 2,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-02-03 22:04",
        "last_payment": "2023-03-03 22:07",
        "mrr": 0,
        "mrr_change_thirty_days": -49,
        "outstanding_balance": 49,
        "active_subscriptions": 0,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NeFeyj6SDk3uMI",
        "created": "2023-04-03 23:51",
        "name": "",
        "description": "",
        "email": "noonevening@gmail.com",
        "net_volume": 50,
        "gross_volume": 50,
        "payment_count": 1,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-04-03 23:53",
        "last_payment": "2023-04-03 23:53",
        "mrr": 50,
        "mrr_change_thirty_days": 50,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_Nd11W4dSs7wC9x",
        "created": "2023-03-31 16:39",
        "name": "",
        "description": "",
        "email": "yaeljakobov@gmail.com",
        "net_volume": 50,
        "gross_volume": 50,
        "payment_count": 1,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-03-31 16:41",
        "last_payment": "2023-03-31 16:41",
        "mrr": 0,
        "mrr_change_thirty_days": -50,
        "outstanding_balance": 0,
        "active_subscriptions": 0,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NcNuQvaJQRE3r2",
        "created": "2023-03-30 00:14",
        "name": "",
        "description": "",
        "email": "alexandrak.sales@gmail.com",
        "net_volume": 100,
        "gross_volume": 100,
        "payment_count": 2,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-03-30 00:15",
        "last_payment": "2023-04-30 01:17",
        "mrr": 50,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NUPSM1lovg8Yzi",
        "created": "2023-03-08 17:19",
        "name": "",
        "description": "",
        "email": "jsultan@location.ventures",
        "net_volume": 100,
        "gross_volume": 100,
        "payment_count": 2,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-03-08 17:19",
        "last_payment": "2023-04-08 18:22",
        "mrr": 50,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_Mz5CeD6H35P4yg",
        "created": "2022-12-15 02:19",
        "name": "Cory Rovens",
        "description": "",
        "email": "cory.rovens@gmail.com",
        "net_volume": 150,
        "gross_volume": 150,
        "payment_count": 5,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2022-12-15 02:19",
        "last_payment": "2023-04-15 03:22",
        "mrr": 30,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_Mz54ENVn0kZjfW",
        "created": "2022-12-15 02:11",
        "name": "2703 Oak Park Dr",
        "description": "",
        "email": "jnnyberg@hotmail.com",
        "net_volume": 150,
        "gross_volume": 150,
        "payment_count": 5,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2022-12-15 02:11",
        "last_payment": "2023-04-15 03:17",
        "mrr": 30,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_N95yK0ghWkviLJ",
        "created": "2023-01-10 19:47",
        "name": "Jordan L Duvall",
        "description": "",
        "email": "j.river2132@gmail.com",
        "net_volume": 200,
        "gross_volume": 200,
        "payment_count": 4,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-01-17 20:50",
        "last_payment": "2023-04-17 20:52",
        "mrr": 50,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NnY2eSiLV2jIcb",
        "created": "2023-04-28 19:27",
        "name": "Connor J Streit",
        "description": "",
        "email": "connorce814@gmail.com",
        "net_volume": 1000,
        "gross_volume": 1000,
        "payment_count": 1,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-04-28 19:28",
        "last_payment": "2023-04-28 19:28",
        "mrr": 1000,
        "mrr_change_thirty_days": 1000,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_Na7dFdfOvW3fEj",
        "created": "2023-03-23 23:17",
        "name": "",
        "description": "",
        "email": "tpowers339@icloud.com",
        "net_volume": 100,
        "gross_volume": 100,
        "payment_count": 2,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-03-23 23:18",
        "last_payment": "2023-04-24 00:21",
        "mrr": 0,
        "mrr_change_thirty_days": -50,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NZw0eCVljG2dMz",
        "created": "2023-03-23 11:16",
        "name": "Stevie Gonzalez",
        "description": "",
        "email": "steviegonzalez@ymail.com",
        "net_volume": 100,
        "gross_volume": 100,
        "payment_count": 2,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-03-30 12:18",
        "last_payment": "2023-04-30 12:18",
        "mrr": 50,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NMJt6RkcXpVcTM",
        "created": "2023-02-15 03:01",
        "name": "",
        "description": "",
        "email": "kylefroseth@gmail.com",
        "net_volume": 150,
        "gross_volume": 150,
        "payment_count": 3,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-02-15 03:02",
        "last_payment": "2023-04-15 04:07",
        "mrr": 50,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NJEg2qOFvpro3W",
        "created": "2023-02-06 21:27",
        "name": "",
        "description": "",
        "email": "john@techvestor.com",
        "net_volume": 150,
        "gross_volume": 150,
        "payment_count": 3,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-02-06 21:29",
        "last_payment": "2023-04-06 22:32",
        "mrr": 50,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NAxYhMMU10pzzb",
        "created": "2023-01-15 19:12",
        "name": "Sweet Stay Rentals",
        "description": "",
        "email": "alexandria.nicole.salgado@gmail.com",
        "net_volume": 196,
        "gross_volume": 196,
        "payment_count": 4,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-01-22 20:13",
        "last_payment": "2023-04-22 20:15",
        "mrr": 49,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_N95rtyfO3qEe7H",
        "created": "2023-01-10 19:40",
        "name": "Joy Sakonyi",
        "description": "",
        "email": "joy.sakonyi@gmail.com",
        "net_volume": 200,
        "gross_volume": 200,
        "payment_count": 4,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-01-17 20:42",
        "last_payment": "2023-04-17 20:42",
        "mrr": 0,
        "mrr_change_thirty_days": -50,
        "outstanding_balance": 0,
        "active_subscriptions": 0,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NTosFgHtoNZBFc",
        "created": "2023-03-07 03:30",
        "name": "",
        "description": "",
        "email": "contact@sovrnlife.com",
        "net_volume": 98,
        "gross_volume": 98,
        "payment_count": 2,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-03-14 18:37",
        "last_payment": "2023-04-14 18:41",
        "mrr": 49,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NFv9Apl8ZPiHsA",
        "created": "2023-01-29 01:03",
        "name": "",
        "description": "",
        "email": "ryannemcruz@gmail.com",
        "net_volume": 200,
        "gross_volume": 200,
        "payment_count": 4,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-01-29 01:05",
        "last_payment": "2023-04-29 02:06",
        "mrr": 50,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NhWjIEhMXIkWVl",
        "created": "2023-04-12 17:41",
        "name": "",
        "description": "",
        "email": "nexxlevel023@gmail.com",
        "net_volume": 53.5,
        "gross_volume": 53.5,
        "payment_count": 1,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-04-19 18:47",
        "last_payment": "2023-04-19 18:47",
        "mrr": 53.5,
        "mrr_change_thirty_days": 53.5,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NdnOFwgUiGZqKh",
        "created": "2023-04-02 18:39",
        "name": "",
        "description": "",
        "email": "tianapontimorales@gmail.com",
        "net_volume": 50,
        "gross_volume": 50,
        "payment_count": 1,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-04-02 18:39",
        "last_payment": "2023-04-02 18:39",
        "mrr": 50,
        "mrr_change_thirty_days": 50,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_Nd63aPJrjiBWYk",
        "created": "2023-03-31 21:51",
        "name": "",
        "description": "",
        "email": "marckendyantenor7@gmail.com",
        "net_volume": 50,
        "gross_volume": 50,
        "payment_count": 1,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-03-31 21:52",
        "last_payment": "2023-03-31 21:52",
        "mrr": 0,
        "mrr_change_thirty_days": -50,
        "outstanding_balance": 0,
        "active_subscriptions": 0,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NcPiUOuLNE2RvJ",
        "created": "2023-03-30 02:06",
        "name": "",
        "description": "",
        "email": "bellwoodinvest@gmail.com",
        "net_volume": 100,
        "gross_volume": 100,
        "payment_count": 2,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-03-30 02:10",
        "last_payment": "2023-04-30 03:11",
        "mrr": 50,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NL2kWkO7WkAsck",
        "created": "2023-02-11 17:14",
        "name": "",
        "description": "",
        "email": "concierge@intothebox.net",
        "net_volume": 147,
        "gross_volume": 147,
        "payment_count": 3,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-02-18 18:21",
        "last_payment": "2023-04-18 18:23",
        "mrr": 0,
        "mrr_change_thirty_days": -49,
        "outstanding_balance": 0,
        "active_subscriptions": 0,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NOEi1ZEh6N6sTT",
        "created": "2023-02-20 05:48",
        "name": "",
        "description": "",
        "email": "dnako@worcester.edu",
        "net_volume": 150,
        "gross_volume": 150,
        "payment_count": 3,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-02-20 05:51",
        "last_payment": "2023-04-20 06:52",
        "mrr": 50,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NKrF8wAa72IPzN",
        "created": "2023-02-11 05:22",
        "name": "",
        "description": "",
        "email": "georgeramosjr@gmail.com",
        "net_volume": 150,
        "gross_volume": 150,
        "payment_count": 3,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-02-11 05:22",
        "last_payment": "2023-04-11 06:26",
        "mrr": 50,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_Ne7gDYBSF86QAL",
        "created": "2023-04-03 15:36",
        "name": "",
        "description": "",
        "email": "ejsnead@yahoo.com",
        "net_volume": 50,
        "gross_volume": 50,
        "payment_count": 1,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-04-03 15:38",
        "last_payment": "2023-04-03 15:38",
        "mrr": 0,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 0,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NZmoirrBKlFpJo",
        "created": "2023-03-23 01:46",
        "name": "",
        "description": "",
        "email": "zser26@gmail.com",
        "net_volume": 100,
        "gross_volume": 100,
        "payment_count": 2,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-03-23 01:47",
        "last_payment": "2023-04-23 02:50",
        "mrr": 50,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NN2sUxec2JHw0O",
        "created": "2023-02-17 01:30",
        "name": "",
        "description": "",
        "email": "whitleigh23@gmail.com",
        "net_volume": 150,
        "gross_volume": 150,
        "payment_count": 3,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-02-17 01:32",
        "last_payment": "2023-04-17 02:32",
        "mrr": 50,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NEfIIo5gcPqmpM",
        "created": "2023-01-25 16:37",
        "name": "",
        "description": "",
        "email": "gsunlimitedsolutions@gmail.com",
        "net_volume": 200,
        "gross_volume": 200,
        "payment_count": 4,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-01-25 16:39",
        "last_payment": "2023-04-25 17:42",
        "mrr": 50,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NkdDZHeeJWLL2i",
        "created": "2023-04-21 00:35",
        "name": "",
        "description": "",
        "email": "Stephl50@outlook.com",
        "net_volume": 321,
        "gross_volume": 321,
        "payment_count": 1,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-04-28 01:43",
        "last_payment": "2023-04-28 01:43",
        "mrr": 26.75,
        "mrr_change_thirty_days": 26.75,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_Njj5RstxMm9vE1",
        "created": "2023-04-18 14:36",
        "name": "",
        "description": "",
        "email": "shane@riverlifehold.com",
        "net_volume": 321,
        "gross_volume": 321,
        "payment_count": 1,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-04-25 15:41",
        "last_payment": "2023-04-25 15:41",
        "mrr": 26.75,
        "mrr_change_thirty_days": 26.75,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NZeJNJgtZ4wkNL",
        "created": "2023-03-22 16:59",
        "name": "",
        "description": "",
        "email": "nikko@mail.com",
        "net_volume": 100,
        "gross_volume": 100,
        "payment_count": 2,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-03-22 17:00",
        "last_payment": "2023-04-22 18:07",
        "mrr": 50,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NkeoDQ3l3HmS9J",
        "created": "2023-04-21 02:15",
        "name": "",
        "description": "",
        "email": "cocoa141@gmail.com",
        "net_volume": 321,
        "gross_volume": 321,
        "payment_count": 1,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-04-21 02:27",
        "last_payment": "2023-04-21 02:27",
        "mrr": 26.75,
        "mrr_change_thirty_days": 26.75,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "e68f06c2-53db-42d9-a8e0-b6a77e9bb5d3",
        "Affiliate (metadata)": "Shauntae  Williams <shauntae@morepreciousthanjewels.net>",
        "Campaign (metadata)": "Fetchit Ambassadors: 50% commission on all payments",
        "Link (metadata)": "shauntae",
        "View in Rewardful (metadata)": "https://app.getrewardful.com/referrals/e68f06c2-53db-42d9-a8e0-b6a77e9bb5d3",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "Guest",
        "created": "2023-04-29 17:25",
        "name": "Sarah Carlson",
        "description": "",
        "email": "cj.co@outlook.com",
        "net_volume": 200,
        "gross_volume": 200,
        "payment_count": 1,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-04-29 17:25",
        "last_payment": "2023-04-29 17:25",
        "mrr": 0,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 0,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NLqMosCpWaiDlF",
        "created": "2023-02-13 20:30",
        "name": "",
        "description": "",
        "email": "info@romanocapital.io",
        "net_volume": 150,
        "gross_volume": 150,
        "payment_count": 3,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-02-13 20:32",
        "last_payment": "2023-04-13 21:34",
        "mrr": 50,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NcRm8tAa0GqnjF",
        "created": "2023-03-30 04:15",
        "name": "",
        "description": "",
        "email": "jriccaldo@hotmail.com",
        "net_volume": 49,
        "gross_volume": 49,
        "payment_count": 1,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-04-06 05:20",
        "last_payment": "2023-04-06 05:20",
        "mrr": 49,
        "mrr_change_thirty_days": 49,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NFwEDHkNrNvEG6",
        "created": "2023-01-29 02:11",
        "name": "",
        "description": "",
        "email": "jazminkirkman@gmail.com",
        "net_volume": 147,
        "gross_volume": 147,
        "payment_count": 3,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-02-16 20:37",
        "last_payment": "2023-04-16 20:38",
        "mrr": 49,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_N95rHuK1WMCj09",
        "created": "2023-01-10 19:40",
        "name": "Terry Morse",
        "description": "",
        "email": "viraest@hotmail.com",
        "net_volume": 200,
        "gross_volume": 200,
        "payment_count": 4,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-01-17 20:42",
        "last_payment": "2023-04-17 20:42",
        "mrr": 50,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NEhS4M5ZbfJ0Ni",
        "created": "2023-01-25 18:50",
        "name": "",
        "description": "",
        "email": "lafernandez211@gmail.com",
        "net_volume": 150,
        "gross_volume": 150,
        "payment_count": 3,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-01-25 18:51",
        "last_payment": "2023-03-25 19:54",
        "mrr": 50,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 50,
        "active_subscriptions": 0,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_N98FRWS9LyXzlo",
        "created": "2023-01-10 22:07",
        "name": "Bryan M Autrey",
        "description": "",
        "email": "bautrey77@att.net",
        "net_volume": 200,
        "gross_volume": 200,
        "payment_count": 4,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-01-17 23:08",
        "last_payment": "2023-04-17 23:10",
        "mrr": 50,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_N1g9FYlSfj5bG7",
        "created": "2022-12-22 00:38",
        "name": "David Rosenbeck",
        "description": "",
        "email": "davidrosenbeckrei@gmail.com",
        "net_volume": 50,
        "gross_volume": 50,
        "payment_count": 5,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2022-12-22 00:38",
        "last_payment": "2023-04-22 01:41",
        "mrr": 10,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_Mzi4aExOVnnOKl",
        "created": "2022-12-16 18:28",
        "name": "Andrea Saade",
        "description": "",
        "email": "94amejia@gmail.com",
        "net_volume": 150,
        "gross_volume": 150,
        "payment_count": 5,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2022-12-16 18:28",
        "last_payment": "2023-04-16 19:33",
        "mrr": 30,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_Mz55F1S8n1Vcf2",
        "created": "2022-12-15 02:11",
        "name": "Casey Woodburn",
        "description": "",
        "email": "woodburnassets@gmail.com",
        "net_volume": 150,
        "gross_volume": 150,
        "payment_count": 5,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2022-12-15 02:11",
        "last_payment": "2023-04-15 03:13",
        "mrr": 0,
        "mrr_change_thirty_days": -30,
        "outstanding_balance": 0,
        "active_subscriptions": 0,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_Na7hq2tjdDsimu",
        "created": "2023-03-23 23:21",
        "name": "",
        "description": "",
        "email": "leahfuente1013@gmail.com",
        "net_volume": 100,
        "gross_volume": 100,
        "payment_count": 2,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-03-23 23:21",
        "last_payment": "2023-04-24 00:24",
        "mrr": 50,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "8b1938c9-97cc-4266-b945-fc52008ca2b6",
        "Affiliate (metadata)": "leah Fuentes <leahfuente1013@gmail.com>",
        "Campaign (metadata)": "Fetchit Ambassadors: 50% commission on all payments",
        "Link (metadata)": "leah",
        "View in Rewardful (metadata)": "https://app.getrewardful.com/referrals/8b1938c9-97cc-4266-b945-fc52008ca2b6",
        "Referral deactivated (metadata)": ""
    },
    {
        "customer_id": "cus_NSY3k9Ty0gRbGC",
        "created": "2023-03-03 18:03",
        "name": "",
        "description": "",
        "email": "philliphayes10@gmail.com",
        "net_volume": 100,
        "gross_volume": 100,
        "payment_count": 2,
        "refund_volume": 0,
        "dispute_losses": 0,
        "first_payment": "2023-03-03 18:04",
        "last_payment": "2023-04-03 19:09",
        "mrr": 50,
        "mrr_change_thirty_days": 0,
        "outstanding_balance": 0,
        "active_subscriptions": 1,
        "trial_end_date": "",
        "referral (metadata)": "",
        "Affiliate (metadata)": "",
        "Campaign (metadata)": "",
        "Link (metadata)": "",
        "View in Rewardful (metadata)": "",
        "Referral deactivated (metadata)": ""
    }
]

const xy = async (email: string) => {
    if (email === undefined) return;
    const user = await prisma.user.findUnique({
        where: {
            email
        }
    })

    if (user) {
        await prisma.user.update({
            where: {
                email
            },
            data: {
                plan: "BOTH"
            }
        })
    }
}

export default async function handler(
    req: NextApiRequest,
    res: NextApiResponse<Data>
) {
    if (req.method !== 'GET') {
        return res.status(400).json({ name: 'Bad Request' })
    }

    for (let i = 0; i < users.length; i++) {
        const user = users[i];
        await xy(user.email);
        console.log("done " + i)
    }


    res.status(200).json({ msg: "completed." })
}
